const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),N=require('../src/notation.js'),{lesson:l}=require('../src/advanced.js');
test('进阶谱 73 小节逐节四拍，原调与高音区',()=>{assert.equal(l.bars.length,73);assert.equal(C.validateLesson(l),true);l.bars.forEach((b,i)=>assert.ok(Math.abs(C.barBeats(l,i)-4)<1e-9));assert.equal(l.fifths,1);assert.equal(l.mode,'minor');assert.deepEqual(l.bars[0].map(e=>e.pitch),['F#4','F#4','E4','F#4','F#4','E4']);assert.ok(l.bars.slice(1,7).every(b=>b.length===1&&b[0].measureRest));assert.equal(C.timeline(l,{tempo:60}).duration,292);});
test('一二房重复路线正确，分段和未勾选不跳转',()=>{const p=C.timeline(l,{tempo:60,repeat:true}),route=p.entries.filter(e=>e.index===0).map(e=>e.bar+1);assert.deepEqual(route,[...Array.from({length:65},(_,i)=>i+1),...Array.from({length:23},(_,i)=>i+34),...Array.from({length:8},(_,i)=>i+66)]);assert.equal(p.duration,384);assert.equal(p.passes,2);assert.equal(p.clicks.length,384);assert.equal(C.timeline(l,{from:57,to:65,repeat:true,tempo:60}).duration,36);assert.equal(C.timeline(l,{tempo:30,repeat:true,countIn:true}).duration,776);});
test('三连音按 2/3 拍发声，严格校验完整分组',()=>{const p=C.timeline(l,{from:59,to:59,tempo:60});assert.equal(p.entries.length,6);assert.equal(p.entries[1].time,2/3);assert.equal(p.entries[3].time,2);assert.ok(Math.abs(p.duration-4)<1e-9);const broken=structuredClone(l);broken.bars[0][1].tuplet.index=0;assert.throws(()=>C.validateLesson(broken),/三连音/);});
test('跨小节延音、连弓与独立重新发音',()=>{const p=C.timeline(l,{from:66,to:73,tempo:60}),f=p.entries.find(e=>e.bar===65&&e.index===2);assert.equal(f.sustain,3.5);assert.equal(p.entries.find(e=>e.bar===66&&e.index===0).continuation,true);assert.equal(p.entries.find(e=>e.bar===70).continuation,undefined);assert.equal(p.entries.find(e=>e.bar===70).sustain,8);assert.equal(p.entries.find(e=>e.bar===72).continuation,undefined);assert.equal(l.bars[21][0].tie,undefined);});
test('参考指法的音高一致，第四把位和伸张可见',()=>{const open={G:43,D:50,A:57},normal=[0,2,3,4,5],fourth=[0,5,6,7,8];l.bars.flat().filter(e=>e.pitch).forEach(e=>assert.equal(open[e.string]+(e.position==='IV'?fourth:normal)[e.finger]+(e.extension==='forward'?1:e.extension==='back'?-1:0),C.pitchInfo(e.pitch).midi));assert.match(N.renderSystem(l,0,2,{fingers:true}),/4伸·IV/);});
test('MusicXML 与 SVG 包含三连音、连弓、延音、一二房与原谱速度',()=>{const x=N.musicxml(l,true,116);assert.match(x,/<divisions>24<\/divisions>/);assert.equal((x.match(/<time-modification>/g)||[]).length,18);assert.equal((x.match(/<tuplet number="1" type="start"/g)||[]).length,6);assert.match(x,/<duration>16<\/duration><type>quarter/);assert.match(x,/<repeat direction="forward"/);assert.equal((x.match(/<repeat direction="backward"/g)||[]).length,1);assert.match(x,/<ending number="2" type="start"/);assert.match(x,/<sound tempo="116"/);assert.match(x,/<slur number="1" type="start"/);assert.match(N.renderSystem(l,56,2),/class="volta"/);assert.match(N.renderSystem(l,58,2),/class="tuplet"/);assert.match(N.renderSystem(l,20,2),/class="slur"/);});

test('跨小节延音不使后续独立 F 音省略还原号',()=>{const svg=N.renderSystem(l,66,1);assert.equal((svg.match(/E261/g)||[]).length,1);assert.equal(l.bars[59][0].pitch,'D3');assert.equal(l.bars[60][0].pitch,'D3');});
