const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const cacheHome=process.env.HOME||process.env.USERPROFILE||'',playwrightCandidates=[process.env.PLAYWRIGHT_PATH,path.join(cacheHome,'.cache','codex-runtimes','codex-primary-runtime','dependencies','node','node_modules','playwright'),'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'].filter(Boolean),playwrightPath=playwrightCandidates.find(fs.existsSync);
if(!playwrightPath)throw Error('找不到 Playwright；请设置 PLAYWRIGHT_PATH 指向 playwright 包目录。');
const {chromium}=require(playwrightPath);
const ROOT=path.resolve(__dirname,'..'),qa=path.join(ROOT,'qa');fs.mkdirSync(qa,{recursive:true});
(async()=>{
 const executablePath=process.env.BROWSER_PATH||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined),browser=await chromium.launch({...(executablePath?{executablePath}:{}),headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4317');await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('#title').textContent(),'风之歌');assert.equal(await page.locator('#score .score-line').count(),4);assert.equal(await page.locator('link[rel=icon]').getAttribute('href'),'cello-icon.svg?v=2');assert.equal(await page.locator('.brand-icon').count(),0);
 await page.screenshot({path:path.join(qa,'desktop-practice.png'),fullPage:true});await page.click('#answers');await page.check('[data-layer=jianpu]');await page.screenshot({path:path.join(qa,'desktop-answers.png'),fullPage:true});
 const glyphs=await page.evaluate(()=>({font:document.fonts.check('48px Bravura'),bars:CelloApp.lesson().bars.length}));assert.equal(glyphs.font,true);assert.equal(glyphs.bars,14);
 await page.selectOption('#from','3');await page.selectOption('#to','6');await page.selectOption('#tempo','20');await page.uncheck('#countIn');await page.check('#repeat');await page.click('#play');await page.waitForTimeout(300);
 let plan=await page.evaluate(()=>CelloApp.plan());assert.equal(plan.passes,1);assert.equal(plan.duration,24);assert.equal(plan.entries[0].pitch,'B3');assert.equal(plan.entries[0].duration,1.5);assert.equal(await page.locator('#score .active').count(),1);await page.click('#stop');assert.equal(await page.locator('#score .active').count(),0);
 await page.selectOption('#tempo','30');await page.click('#play');await page.waitForTimeout(100);plan=await page.evaluate(()=>CelloApp.plan());assert.equal(plan.duration,16);assert.equal(plan.entries[0].duration,1);await page.click('#stop');
 await page.selectOption('#from','10');await page.selectOption('#to','2');await page.click('#play');assert.match(await page.locator('#playerStatus').textContent(),/结束小节/);await page.click('#whole');
 await page.click('[data-tab=theoryPanel]');assert.equal(await page.locator('#theory .card').count(),3);
 await page.click('[data-tab=recordsPanel]');await page.fill('#recordNote','第 3 小节：1 指保持。<img src=x onerror=alert(1)>');await page.fill('#recordTempo','30');await page.click('#recordForm button');assert.equal(await page.locator('#records .record-entry').count(),1);assert.equal(await page.locator('#records img').count(),0);
 const [download]=await Promise.all([page.waitForEvent('download'),page.click('#exportRecords')]);const backup=path.join(qa,'test-backup.json');await download.saveAs(backup);const data=JSON.parse(fs.readFileSync(backup,'utf8'));assert.equal(data.records.length,1);
 await page.setInputFiles('#importRecords',backup);assert.match(await page.locator('#recordMessage').textContent(),/跳过重复 1/);assert.equal(await page.locator('#records .record-entry').count(),1);
 const altered=JSON.parse(JSON.stringify(data));altered.records[0].note='来自另一台电脑的修改';const conflict=path.join(qa,'test-conflict.json');fs.writeFileSync(conflict,JSON.stringify(altered));await page.setInputFiles('#importRecords',conflict);assert.equal(await page.locator('#records .record-entry').count(),2);await page.setInputFiles('#importRecords',conflict);assert.equal(await page.locator('#records .record-entry').count(),2);
 await page.setInputFiles('#importRecords',{name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});assert.match(await page.locator('#recordMessage').textContent(),/未导入/);assert.equal(await page.locator('#records .record-entry').count(),2);
 await page.fill('#recordNote','未保存的风之歌备注');await page.click('a[href="#d-major-up"]');await page.waitForFunction(()=>CelloApp.lesson().id==='d-major-up');assert.equal(await page.locator('#recordNote').inputValue(),'');await page.fill('#recordNote','音阶草稿');await page.click('a[href="#song-of-the-wind"]');await page.waitForFunction(()=>CelloApp.lesson().id==='song-of-the-wind');assert.equal(await page.locator('#recordNote').inputValue(),'未保存的风之歌备注');
 // A second computer/profile imports the export independently.
 const second=await browser.newContext();const p2=await second.newPage();await p2.goto('http://127.0.0.1:4317');await p2.click('[data-tab=recordsPanel]');await p2.setInputFiles('#importRecords',backup);assert.equal(await p2.locator('#records .record-entry').count(),1);await second.close();
 await page.click('[data-tab=scorePanel]');await page.click('#hideAnswers');await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);assert.equal(await page.locator('#score .score-line').count(),7);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(qa,'mobile.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.waitForTimeout(250);await page.selectOption('#tempo','60');
 const space=()=>page.evaluate(()=>document.querySelector('#scorePanel').dispatchEvent(new KeyboardEvent('keydown',{code:'Space',bubbles:true,cancelable:true})));
 await space();await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>CelloApp.playbackState()),'playing');assert.equal(await page.locator('#play').textContent(),'暂停');
 await space();assert.equal(await page.evaluate(()=>CelloApp.playbackState()),'paused');assert.equal(await page.locator('#play').textContent(),'▶ 继续播放');
 await space();await page.waitForTimeout(40);assert.equal(await page.evaluate(()=>CelloApp.playbackState()),'playing');await page.click('#stop');
 await page.evaluate(()=>document.querySelector('#printRoot').innerHTML=CelloApp.printHtml());const windPdf=path.join(ROOT,'dist/scores/song-of-the-wind.pdf');if(!fs.existsSync(windPdf))await page.pdf({path:windPdf,preferCSSPageSize:true,printBackground:true});
 let print='';for(const id of ['d-major-up','d-major-down','d-major-return']){await page.goto('http://127.0.0.1:4317/#'+id);await page.evaluate(()=>document.fonts.ready);print+=await page.evaluate(()=>CelloApp.printHtml());}
 await page.evaluate(html=>{window.onbeforeprint=null;document.querySelector('#printRoot').innerHTML=html;},print);
 // beforeprint handler rewrites the current lesson: print all scale pages in an isolated page.
 const printPage=await context.newPage();const style=await page.locator('style').textContent();await printPage.setContent('<html><head><style>'+style+'</style></head><body><div id="printRoot">'+print+'</div></body></html>');await printPage.evaluate(()=>document.fonts.ready);
 const scalePdf=path.join(ROOT,'dist/scores/d-major-scales.pdf');if(!fs.existsSync(scalePdf))await printPage.pdf({path:scalePdf,preferCSSPageSize:true,printBackground:true});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(qa,'browser-results.json'),JSON.stringify({desktop:true,mobile:true,tempo20and30:true,range:true,recordsImportExport:true,conflictsPreserved:true,draftsPreserved:true,secondProfileImport:true,errors},null,2));console.log('Browser checks passed; PDF outputs created.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
