const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../src/core.js'),lib=require('../src/library.js'),notation=require('../src/notation.js');
const wind=lib.lessons[0];
test('教材原曲：14 小节，2/4 拍，逐小节两拍',()=>{assert.equal(wind.bars.length,14);assert.deepEqual(wind.meter,[2,4]);lib.lessons.forEach(l=>assert.equal(core.validateLesson(l),true));});
test('独立核对原曲音列，保持休止与换气',()=>{const expected=['D3 E3 F#3 G3','A3 A3 A3 A3','B3 G3 D4 B3','A3 -','B3 G3 D4 B3','A3 -','A3 G3 G3 G3','G3 F#3 F#3 F#3','F#3 E3 E3 E3','D3 F#3 A3','A3 G3 G3 G3','G3 F#3 F#3 F#3','F#3 E3 E3 E3','D3 -'];assert.deepEqual(wind.bars.map(b=>b.map(e=>e.pitch||'-').join(' ')),expected);assert.equal(wind.bars[9][2].breath,true);assert.deepEqual(wind.bars[2].map(e=>[e.string,e.finger]),[['A',1],['D',4],['A',4],['A',1]]);});
test('20 / 30 BPM：八分音符时长分别为 1.5 秒和 1 秒',()=>{for(const tempo of [20,30]){const p=core.timeline(wind,{tempo,countIn:false,repeat:false});assert.equal(p.entries[0].duration,30/tempo);assert.equal(p.duration,28*60/tempo);assert.equal(p.entries[1].time,30/tempo);}});
test('整曲反复两遍，分段不意外扩展为全曲',()=>{assert.equal(core.timeline(wind,{tempo:60,repeat:true}).duration,56);const p=core.timeline(wind,{from:3,to:6,tempo:60,repeat:true,countIn:true});assert.equal(p.passes,1);assert.equal(p.duration,10);assert.equal(p.entries[0].bar,2);assert.equal(p.entries.at(-1).bar,5);assert.equal(p.clicks.filter(e=>e.pre).length,2);assert.throws(()=>core.timeline(wind,{from:7,to:2}));});
test('音高、谱面位置和八度一致',()=>{assert.equal(core.pitchInfo('D3').midi,50);assert.equal(core.pitchInfo('A3').hz,220);assert.equal(core.pitchInfo('F#3').midi,54);assert.equal(core.pitchInfo('D4').y,54);assert.equal(core.pitchInfo('C#4').y,60);});
const record={id:'r1',lessonId:'song-of-the-wind',date:'2026-09-07',tempo:30,status:'练习中',note:'第 3 小节',createdAt:'2026-09-07T10:00:00Z'};
test('备份重复导入幂等，冲突保留两份且不改写原记录',()=>{const existing=[record],changed={...record,note:'另一台电脑'};const a=core.mergeRecords(existing,[record,changed]);assert.equal(a.records.length,2);assert.equal(a.duplicates,1);assert.equal(a.conflicts,1);assert.equal(existing.length,1);assert.equal(a.records[0].note,'第 3 小节');const b=core.mergeRecords(a.records,[changed]);assert.equal(b.added,0);assert.equal(b.records.length,2);});
test('无效备份拒绝，内容必须经过类型检查',()=>{assert.throws(()=>core.parseBackup('{}'));assert.throws(()=>core.parseBackup(JSON.stringify({format:'cello-notebook-records',version:1,records:[{...record,tempo:-1}]})));assert.equal(core.parseBackup(JSON.stringify({format:'cello-notebook-records',version:1,records:[record]})).length,1);});
test('MusicXML 包含调号、半拍、指法、下弓和反复',()=>{const x=notation.musicxml(wind,true);assert.match(x,/<fifths>2<\/fifths>/);assert.match(x,/<divisions>8<\/divisions>/);assert.match(x,/<duration>4<\/duration><type>eighth<\/type>/);assert.match(x,/<repeat direction="backward"\/>/);assert.match(x,/<down-bow\/>/);assert.match(x,/<breath-mark\/>/);assert.equal((x.match(/<measure /g)||[]).length,14);});

test('弱起按位置对齐预备拍，首尾互补，反复无额外拍',()=>{const l=lib.lessons.find(l=>l.pickup);const p=core.timeline(l,{tempo:60,countIn:true,repeat:true});assert.equal(l.bars.length,17);assert.equal(p.entries[0].time,1.5);assert.equal(p.entries[1].time,2);assert.equal(p.duration,65.5);assert.equal(p.entries.find(e=>e.pass===1).time,33.5);assert.deepEqual(p.clicks.filter(e=>e.pre).map(e=>e.time),[0,1]);assert.equal(p.clicks.find(e=>!e.pre).time,2);assert.equal(core.timeline(l,{tempo:60}).duration,32);const broken=structuredClone(l);broken.bars[16][0].beats=2;assert.throws(()=>core.validateLesson(broken));const x=notation.musicxml(l);assert.match(x,/<measure number="0" implicit="yes">/);assert.match(x,/<duration>12<\/duration><type>quarter<\/type><dot\/>/);});
test('剩余曲目长度与各变奏节奏核对',()=>{const get=id=>lib.lessons.find(l=>l.id===id);assert.equal(lib.lessons.length,17);assert.equal(get('lightly-row').bars.length,16);assert.equal(get('go-tell-aunt-rhody').bars.length,12);assert.equal(get('c-major-scale').bars.length,4);for(const letter of ['a','b','c','d']){const l=get('twinkle-'+letter);assert.equal(l.bars.length,12);assert.equal(core.timeline(l,{tempo:60}).duration,48);}assert.deepEqual(get('twinkle-a').bars[0].map(e=>e.beats),[.25,.25,.25,.25,.5,.5,.25,.25,.25,.25,.5,.5]);assert.equal(get('twinkle-b').bars.flat().filter(e=>!e.pitch).length,24);assert.equal(get('twinkle-d').bars.flat().length,192);assert.match(notation.musicxml(get('twinkle-d')),/<beam number="2">continue<\/beam>/);assert.equal(core.timeline(get('twinkle-d'),{tempo:20}).entries[0].duration,.75);});
test('五月之歌：教材第 9 页的 12 小节、附点节奏与反复',()=>{const l=lib.lessons.find(l=>l.id==='may-song');assert.deepEqual(l.meter,[4,4]);assert.equal(l.bars.length,12);assert.equal(core.timeline(l,{tempo:60,repeat:false}).duration,48);assert.equal(core.timeline(l,{tempo:60,repeat:true}).duration,96);assert.deepEqual(l.bars.map(b=>b.map(e=>e.pitch||'-').join(' ')),['D3 F#3 A3 D4','B3 D4 B3 A3','G3 A3 F#3 D3','E3 D3','A3 A3 G3 F#3','F#3 A3 F#3 E3','A3 A3 G3 F#3','F#3 A3 F#3 E3','D3 F#3 A3 D4','B3 D4 B3 A3','G3 A3 F#3 D3','E3 D3']);assert.deepEqual(l.bars[0].map(e=>e.beats),[1.5,.5,1,1]);assert.equal(l.bars[0][0].bow,'down');assert.equal(l.bars[0][1].bow,'up');assert.match(notation.musicxml(l,true),/<repeat direction="backward"\/>/);});
