(function(){
'use strict';
const {lessons,planned}=CelloLibrary,C=CelloCore,N=CelloNotation,$=s=>document.querySelector(s),KEY='cello-notebook-records-v1';
let current=lessons[0],layers={names:false,strings:false,fingers:false,jianpu:false,bows:true},records=[],storageReady=true,pendingInput=false,initialized=false;
const drafts=new Map();
try{const raw=localStorage.getItem(KEY);if(raw){records=C.parseBackup(raw);}}catch(e){storageReady=false;}
const tempoOptions=[20,30,40,50,60,70,80,90,100,110,120];$('#tempo').innerHTML=tempoOptions.map(t=>`<option value="${t}">${t}</option>`).join('');
$('#library').innerHTML='<div class="nav-label">正在练习</div>'+lessons.map(l=>`<a class="nav-link" href="#${l.id}">${N.esc(l.title)}</a>`).join('')+(planned.length?'<div class="nav-label">第一阶段 · 待录谱</div>'+planned.map(t=>`<div class="planned">${N.esc(t)}</div>`).join(''):'');
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};$('#recordDate').value=localDate();
function selection(){return {from:Number($('#from').value),to:Number($('#to').value)};}
function validSelection(){const r=selection();if(r.to<r.from){$('#playerStatus').textContent='结束小节不能早于起始小节。';return false;}return true;}
function renderScore(){const mobile=innerWidth<=700,per=mobile?(current.systemBars?1:2):(current.systemBars||4),sel=selection(),showSel=sel.from!==1||sel.to!==current.bars.length;let html='';for(let i=0;i<current.bars.length;i+=per)html+=`<div class="score-line">${N.renderSystem(current,i,Math.min(per,current.bars.length-i),layers,showSel?sel:null,true,mobile)}</div>`;$('#score').innerHTML=html;document.querySelectorAll('#score .note-event').forEach(el=>{const play=()=>singleNote(el.dataset.pitch);el.onclick=play;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();play();}};});}
function printHtml(){const per=current.systemBars||4,systemCount=Math.ceil(current.bars.length/per),pages=Math.ceil(systemCount/4),perPage=Math.ceil(systemCount/pages)*per;return [false,true].flatMap(answer=>Array.from({length:pages},(_,page)=>{const start=page*perPage,end=Math.min(current.bars.length,start+perPage);let systems='';for(let i=start;i<end;i+=per)systems+=`<div class="print-score">${N.renderSystem(current,i,Math.min(per,end-i),{names:answer,strings:answer,fingers:answer,jianpu:false,bows:true},null,false)}</div>`;return `<section class="print-page"><h1 class="print-title">${N.esc(current.title)} · ${answer?'辅助版':'练习版'}</h1><div class="print-meta">${N.esc(current.english)} · ${N.esc(current.keyLabel||'D 大调')} · ${current.meter.join('/')} 拍 · 四分音符 = ${$('#tempo').value}${current.repeat?' · 末尾反复':''}<br>${N.esc(current.positionLabel||'第一把位')} / ${N.esc(current.stringsLabel||'D、A 弦')} · 第 ${C.barLabel(current,start)}–${C.barLabel(current,end-1)} 小节 · 日期：________${current.pickup?`<br>弱起 ${current.pickup} 拍，末小节 ${current.meter[0]-current.pickup} 拍，首尾合计 ${current.meter[0]} 拍。`:''}</div>${systems}<div class="print-footer">${answer?'音名、弦名、指法依次分行；指法为本练习的第一把位选择。':'先独立读谱；休止符也要数满拍。'}<br>${N.esc(current.source)}<br>Bravura · SIL Open Font License · ${(answer?pages:0)+page+1} / ${pages*2}</div></section>`;})).join('');}
function loadLesson(){if(initialized)drafts.set(current.id,{note:$('#recordNote').value,date:$('#recordDate').value,tempo:$('#recordTempo').value,status:$('#recordStatus').value});const found=lessons.find(l=>l.id===location.hash.slice(1));const next=found||lessons[0];stop(false);current=next;C.validateLesson(current);document.title=current.title+' · 大提琴练习册';$('#lessonKind').textContent=current.kind+' / '+(current.collection||'铃木第一册学习伴侣');$('#title').textContent=current.title;$('#description').textContent=current.description;$('#chips').innerHTML=[current.meter.join('/')+' 拍',current.keyLabel||'D 大调',(current.pickup?(current.bars.length-1)+' 小节 + 弱起':current.bars.length+' 小节'),current.focus].map(v=>`<span class="chip">${N.esc(v)}</span>`).join('');$('#tempo').value=current.tempo;const draft=drafts.get(current.id);$('#recordTempo').value=draft?.tempo||current.tempo;$('#recordDate').value=draft?.date||localDate();$('#recordStatus').value=draft?.status||'练习中';$('#recordNote').value=draft?.note||'';$('#recordMessage').textContent='';initialized=true;
 const options=current.bars.map((_,i)=>`<option value="${i+1}">${C.barLabel(current,i)}</option>`).join('');$('#from').innerHTML=options;$('#to').innerHTML=options;$('#from').value=1;$('#to').value=current.bars.length;$('#repeatLabel').hidden=!current.repeat;
 $('#scoreHeading').textContent=current.tempoLabel?current.tempoLabel+' · '+current.english:current.english;$('#source').textContent=current.source;$('#tips').innerHTML=current.practiceTips.map(t=>'<li>'+N.esc(t)+'</li>').join('');$('#theory').innerHTML=current.theory.map((t,i)=>`<article class="card"><div class="eyebrow">${String(i+1).padStart(2,'0')}</div><h2>${N.esc(t.title)}</h2><p>${N.esc(t.body)}</p><div class="theory-task">试一试：${N.esc(t.task)}</div></article>`).join('');
 $('#phrases').innerHTML=current.sections.map(s=>`<button data-from="${s.from}" data-to="${s.to}">${N.esc(s.label)} · ${C.barLabel(current,s.from-1)}–${C.barLabel(current,s.to-1)}</button>`).join('');document.querySelectorAll('#phrases button').forEach(b=>b.onclick=()=>{stop();$('#from').value=b.dataset.from;$('#to').value=b.dataset.to;renderScore();$('#playerStatus').textContent=`已选第 ${C.barLabel(current,Number(b.dataset.from)-1)}–${C.barLabel(current,Number(b.dataset.to)-1)} 小节，点击播放。`;});
 document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.hash==='#'+current.id));$('#playerStatus').textContent='先读谱、拍节奏，再播放核对。';renderScore();renderRecords();$('#printRoot').innerHTML=printHtml();}
let ctx=null,activeNodes=new Set(),run=null,frame=null,generation=0;
async function audioReady(){
 // Request the media playback channel before creating/resuming audio in the click handler.
 // Unsupported browsers keep their normal Web Audio behavior.
 try{if(navigator.audioSession)navigator.audioSession.type='playback';}catch{}
 if(!ctx||ctx.state==='closed'){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('当前浏览器不支持音频，请使用 Safari 打开。');ctx=new Audio();}
 if(ctx.state!=='running'){let timeout;try{await Promise.race([ctx.resume(),new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('音频尚未启动，请用 Safari 打开后再次点击播放。')),5000);})]);}finally{clearTimeout(timeout);}}
 if(ctx.state!=='running')throw Error('音频被系统暂停，请再次点击播放。');
}
function tone(hz,start,duration,click=false){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=click?'sine':'triangle';osc.frequency.value=hz;const end=start+duration;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(click?.10:.13,start+.007);gain.gain.setValueAtTime(click?.08:.11,Math.max(start+.008,end-.025));gain.gain.linearRampToValueAtTime(0,end);osc.connect(gain);gain.connect(ctx.destination);osc.start(start);osc.stop(end+.01);activeNodes.add(osc);osc.onended=()=>{activeNodes.delete(osc);osc.disconnect();gain.disconnect();};}
function clearActive(){document.querySelectorAll('.note-event.active').forEach(e=>e.classList.remove('active'));}
function stop(message=true){generation++;if(frame)cancelAnimationFrame(frame);frame=null;run=null;for(const n of activeNodes)try{n.stop();}catch(e){}activeNodes.clear();clearActive();$('#progress').style.width='0%';$('#play').textContent='▶ 播放';if(message)$('#playerStatus').textContent='已停止。';}
async function singleNote(pitch){stop(false);if(!pitch){$('#playerStatus').textContent='休止符：保持安静，但继续数拍。';return;}const token=generation;try{await audioReady();if(token!==generation)return;const p=C.pitchInfo(pitch);tone(p.hz,ctx.currentTime+.03,.7);$('#playerStatus').textContent='单音试听：'+p.name;}catch(e){$('#playerStatus').textContent='音频未能启动，请再点击一次。';}}
async function play(){if(!validSelection())return;stop(false);const token=generation;let plan;try{plan=C.timeline(current,{...selection(),tempo:Number($('#tempo').value),countIn:$('#countIn').checked,repeat:$('#repeat').checked});await audioReady();if(token!==generation)return;}catch(e){$('#playerStatus').textContent=e.message||'请点击重试音频。';return;}
 run={plan,start:ctx.currentTime+.08,nextNote:0,nextClick:0,last:-1,loop:$('#loop').checked,click:$('#metronome').checked,cycle:0};$('#play').textContent='重新开始';$('#playerStatus').textContent='准备播放…';pump();}
function pump(){if(!run)return;const r=run,now=ctx.currentTime,horizon=now+.18;
 while(r.nextNote<r.plan.entries.length&&r.start+r.plan.entries[r.nextNote].time<horizon){const e=r.plan.entries[r.nextNote++];if(e.pitch&&!e.continuation)tone(C.pitchInfo(e.pitch).hz,Math.max(now,r.start+e.time),Math.max(.03,(e.sustain||e.duration)*(e.articulation==='staccato'?.55:.94)));}
 while(r.nextClick<r.plan.clicks.length&&r.start+r.plan.clicks[r.nextClick].time<horizon){const e=r.plan.clicks[r.nextClick++];if(e.pre||r.click)tone(e.strong?1100:780,Math.max(now,r.start+e.time),.035,true);}
 const elapsed=now-r.start;const index=r.plan.entries.findLastIndex(e=>e.time<=elapsed);if(index!==r.last&&index>=0){r.last=index;const e=r.plan.entries[index];clearActive();const el=document.querySelector(`[data-note="${current.id}:${e.bar}:${e.index}"]`);if(el)el.classList.add('active');$('#playerStatus').textContent=`第 ${C.barLabel(current,e.bar)} 小节 · ${e.pitch?C.pitchInfo(e.pitch).name:'休止'} · ${e.beats} 拍${r.plan.passes>1?` · 第 ${e.pass+1} 遍`:''}`;}
 if(index<0){const pre=r.plan.clicks.filter(e=>e.pre&&e.time<=elapsed).at(-1);if(pre)$('#playerStatus').textContent=`预备拍 ${pre.beat} / ${current.meter[0]}`;}
 $('#progress').style.width=Math.max(0,Math.min(100,elapsed/r.plan.duration*100))+'%';
 if(elapsed>=r.plan.duration){if(r.loop){const next=C.timeline(current,{...selection(),tempo:Number($('#tempo').value),countIn:false,repeat:$('#repeat').checked});r.start+=r.plan.duration;r.plan=next;r.nextNote=0;r.nextClick=0;r.last=-1;r.cycle++;}else{stop(false);$('#progress').style.width='100%';$('#playerStatus').textContent='播放完成。试着关掉提示，独立读一遍。';return;}}
 frame=requestAnimationFrame(pump);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&run){stop(false);$('#playerStatus').textContent='离开页面时已暂停；返回后请重新播放。';}});window.addEventListener('pagehide',()=>stop(false));
$('#play').onclick=play;$('#stop').onclick=()=>stop();['tempo','countIn','metronome','loop','repeat'].forEach(id=>$('#'+id).onchange=()=>{stop();if(id==='tempo')$('#recordTempo').value=$('#tempo').value;});['from','to'].forEach(id=>$('#'+id).onchange=()=>{stop();validSelection();renderScore();});$('#whole').onclick=()=>{stop();$('#from').value=1;$('#to').value=current.bars.length;renderScore();};
document.querySelectorAll('[data-layer]').forEach(el=>el.onchange=()=>{layers[el.dataset.layer]=el.checked;renderScore();});function syncLayers(){document.querySelectorAll('[data-layer]').forEach(e=>e.checked=layers[e.dataset.layer]);renderScore();}$('#answers').onclick=()=>{['names','strings','fingers'].forEach(k=>layers[k]=true);syncLayers();};$('#hideAnswers').onclick=()=>{['names','strings','fingers','jianpu'].forEach(k=>layers[k]=false);syncLayers();};
function switchTab(id){document.querySelectorAll('[role=tabpanel]').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('[role=tab]').forEach(t=>t.setAttribute('aria-selected',String(t.dataset.tab===id)));}document.querySelectorAll('[role=tab]').forEach(t=>t.onclick=()=>switchTab(t.dataset.tab));
function saveRecords(candidate){if(!storageReady)throw Error('本地记录无法安全读取；请先导出当前记录并保留原浏览器数据。');const raw=localStorage.getItem(KEY),latest=raw?C.parseBackup(raw):[];const combined=C.mergeRecords(latest,candidate).records;const envelope={format:'cello-notebook-records',version:1,records:combined};localStorage.setItem(KEY,JSON.stringify(envelope));records=combined;}
function renderRecords(){const filtered=records.filter(r=>r.lessonId===current.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('#recordCount').textContent=filtered.length;$('#records').innerHTML=filtered.length?filtered.map(r=>`<article class="card record-entry"><div class="record-meta">${N.esc(r.date)} · ${r.tempo} 拍/分钟 · ${N.esc(r.status)}</div><p class="note-body">${N.esc(r.note||'本次未填写备注。')}</p></article>`).join(''):'<div class="empty">这首曲子还没有练习记录。</div>';if(!storageReady)$('#recordMessage').textContent='当前浏览器无法读取本地记录，原数据未被改写。';}
$('#recordNote').oninput=()=>pendingInput=true;$('#recordForm').onsubmit=e=>{e.preventDefault();const r={id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2),lessonId:current.id,date:$('#recordDate').value,tempo:Number($('#recordTempo').value),status:$('#recordStatus').value,note:$('#recordNote').value.trim(),createdAt:new Date().toISOString()};if(!C.checkRecord(r)){$('#recordMessage').textContent='请检查日期、速度与备注。';return;}try{saveRecords([...records,r]);$('#recordMessage').textContent='已保存在当前浏览器。';$('#recordNote').value='';drafts.delete(current.id);pendingInput=[...drafts.values()].some(d=>d.note);renderRecords();}catch(e){$('#recordMessage').textContent='保存未成功：'+e.message;}};
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('#exportRecords').onclick=()=>download('cello-records-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',JSON.stringify({format:'cello-notebook-records',version:1,exportedAt:new Date().toISOString(),records},null,2),'application/json');
$('#importRecords').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5e6)throw Error('文件超过 5 MB');const incoming=C.parseBackup(await file.text()),merged=C.mergeRecords(records,incoming);saveRecords(merged.records);$('#recordMessage').textContent=`导入完成：新增 ${merged.added} 条，跳过重复 ${merged.duplicates} 条，冲突保留两份 ${merged.conflicts} 条。`;renderRecords();}catch(error){$('#recordMessage').textContent='未导入，原记录保留：'+error.message;}e.target.value='';};
$('#print').onclick=async()=>{stop(false);$('#printRoot').innerHTML=printHtml();await document.fonts.ready;window.print();};window.addEventListener('beforeprint',()=>$('#printRoot').innerHTML=printHtml());
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(renderScore,120);});window.addEventListener('beforeunload',e=>{if(pendingInput){e.preventDefault();e.returnValue='';}});window.addEventListener('hashchange',loadLesson);window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{records=C.mergeRecords(records,C.parseBackup(e.newValue)).records;renderRecords();}catch{}}});
window.CelloApp={lesson:()=>current,selection,plan:()=>run?.plan||null,printHtml,recordCount:()=>records.length,audioState:()=>ctx?.state||'not-started'};
loadLesson();
// Optional browser agent access configures the same controls, without starting audio.
if(document.modelContext?.registerTool){const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});const tools=[
 {name:'read_cello_lesson',title:'Read current cello lesson',description:'Read the current lesson and selected playback range.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {id:current.id,title:current.title,meter:current.meter,bars:current.bars.length,tempo:Number($('#tempo').value),...selection()};}},
 {name:'configure_cello_practice',title:'Configure cello practice',description:'Set the current lesson playback range and tempo; stops current audio and does not begin playback.',inputSchema:{type:'object',properties:{from:{type:'integer',minimum:1},to:{type:'integer',minimum:1},tempo:{type:'integer',enum:tempoOptions}},required:['from','to','tempo'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>!['from','to','tempo'].includes(k))||!tempoOptions.includes(input.tempo))throw Error('无效练习设置');C.timeline(current,input);stop(false);$('#from').value=input.from;$('#to').value=input.to;$('#tempo').value=input.tempo;$('#recordTempo').value=input.tempo;renderScore();$('#playerStatus').textContent=`已设置第 ${input.from}–${input.to} 小节，${input.tempo} 拍/分钟。`;return {lessonId:current.id,...selection(),tempo:input.tempo};}}
 ];for(const tool of tools)try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}
})();
